### POST request with id
POST http://localhost:3001/books
Content-Type: application/json

{
  "title": "harry"
}

### POST request with id
POST http://localhost:3001/books
Content-Type: application/json

{
  "title": "Lord of the Rigs"
}

### GET request with a header
GET http://localhost:3001/books/
Accept: application/json

### GET request with id
GET http://localhost:3001/books/1
Accept: application/json

### PUT request with id
PUT http://localhost:3001/books/1
Content-Type: application/json

{
  "id": 1,
  "title": "Harry Potter"
}

### PUT request with id
PUT http://localhost:3001/books/2
Content-Type: application/json

{
  "id": 1,
  "title": "Lord of the Rings"
}

### DELETE request with id
DELETE http://localhost:3001/books/1
Accept: application/json