import React, { useState } from 'react'
import { Modal, Button } from '../Components';


const ModalPage = () => {
    const [showModal, setShowModal] = useState(false);

    const handleClick = (event) => {
        setShowModal(true)
    }

    const handleClose = () => {
        setShowModal(false);
    }

    const modal = <Modal
        onClose={handleClose}
        actionBar={<div><Button primary onClick={handleClose}>I Accept</Button></div>}
    >
        <p>Here is an important agreement for you to accept</p>
    </Modal >;

    return (
        <div
            className='relative'
        >
            <Button primary
                onClick={handleClick}
            >Open Modal</Button>
            {showModal && modal}
            <div className='pl-40'>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vestibulum justo eros. Suspendisse elementum ligula magna, eu lacinia neque ultricies sit amet. Vestibulum porttitor sem nec scelerisque porttitor. Etiam ac interdum augue. Praesent sit amet hendrerit urna. Proin et suscipit velit. Sed ligula justo, eleifend eget nisi non, gravida varius urna. Nulla porttitor rhoncus ligula, sit amet maximus dui suscipit at. Suspendisse urna leo, bibendum vitae leo id, pulvinar iaculis lectus. Fusce fringilla, libero et sodales posuere, sem metus sagittis velit, vel fringilla dolor odio sit amet lacus. Quisque a auctor justo.

                    Praesent sapien ex, mollis non interdum in, posuere sit amet dui. Morbi ornare, massa eu ullamcorper maximus, turpis nisl tristique lectus, venenatis pretium arcu odio et velit. Aenean bibendum quam risus, fermentum vestibulum leo convallis a. Duis vulputate facilisis augue, ut posuere elit convallis in. Vivamus sollicitudin velit hendrerit, tempor mauris id, aliquam nunc. Pellentesque ultrices dolor at semper bibendum. Duis vel nunc id tellus ultricies sagittis. Donec felis sem, pharetra euismod velit eget, sollicitudin sollicitudin dolor. Integer fringilla nulla in ligula fringilla, quis eleifend leo ultrices. Curabitur dignissim diam quam, rhoncus placerat urna fermentum a. Donec nulla risus, facilisis eget fringilla quis, lacinia quis orci. Suspendisse ante eros, porta nec arcu id, eleifend elementum magna. Cras a purus lacinia, cursus leo id, fermentum nunc.

                    Nam venenatis libero vel lorem tempus, ut aliquet nunc pharetra. Integer tincidunt turpis a semper aliquam. In justo nunc, sodales eu erat quis, venenatis mattis odio. Vivamus ut elit tellus. Pellentesque pellentesque, justo ac commodo interdum, risus lorem ultrices turpis, eu pretium magna diam a ligula. Sed congue tellus felis, eget viverra lectus hendrerit ut. Nam nibh sapien, convallis ac pretium vitae, iaculis vel tellus.

                    Pellentesque a augue et massa tincidunt maximus in vitae diam. Cras ullamcorper, dolor ac rhoncus tempus, lacus quam cursus elit, id ultricies ex tortor ac ante. Vestibulum diam ligula, pretium in tincidunt sit amet, tempus quis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida metus justo, ut interdum mauris varius et. Aliquam at nisi faucibus, dictum eros sed, accumsan libero. Vivamus et vulputate elit, in elementum risus.

                    Pellentesque consectetur convallis fringilla. Pellentesque eu molestie felis. Etiam eget molestie turpis. Vestibulum feugiat elit ut porttitor tincidunt. Vestibulum convallis elit ac pellentesque gravida. Aenean mollis quam lacus, eget mattis odio sollicitudin eget. Integer sodales dapibus nunc sed malesuada. Suspendisse potenti. Donec blandit ante nec vulputate ultrices. Donec blandit justo et vehicula vulputate. Quisque et tincidunt enim, ac euismod metus. Pellentesque nec magna eget ipsum pharetra ultrices.
                </p>
            </div>
        </div>
    )
}

export default ModalPage;
